### PR TITLE
agent-js: fix "DISABLED" evidence sent to tmstore

### LINKED ISSUE #5: agent-js: evidence is sent as DISABLED to the store
### Actual behavior

The tmstore transaction contains state: DISABLED
This occurs when no `fossilizerHttpClient` is passed to the agent. In this case, the evidence will (currently) only be edited if the `tmstore` adapter is being used. If we implement some other blockchain store adapter, like hyperledger fabric, the evidence will also be modified after it is sent by the agent.

- Do we want to send an empty evidence to the store ? Or do we want to send `evidence: "QUEUED"` in segment.meta if the store adapter is `tmstore`  and "DISABLED" in other cases ?

### PR DESCRIPTION
**Pull request by simonvadee**
Fixes #5 
Typo in README has been fixed.

### CODE REVIEW

**Comment by simonvadee** [comment]
yes it does, since { state: "PENDING" } is already added by tmpop in the evidence field

File: packages/agent-js/src/process.js [hunk 1]
```diff
@@ -200,9 +194,7 @@ export default class Process {
     return this.storeClient
       .getSegment(this.name, linkHash)
       .then(segment => {
-        Object.assign(segment.meta.evidence, evidence, {
-          state: COMPLETE
-        });
+        Object.assign(segment.meta.evidence, Object.assign(evidence, { state: COMPLETE }));
```
Comment (such) [inline packages/agent-js/src/process.js]: What does this change?

Comment (simonvadee) [reply packages/agent-js/src/process.js]: my bad, I forgot to change it back after my last commit.
